version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/rag
permissions:
  - object: /home/ubuntu/rag
    pattern: "**"
    owner: root
    group: root
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 1200
      runas: root
  AfterInstall:
    - location: scripts/build_run.sh
      timeout: 600
      runas: root
file_exists_behavior: OVERWRITE
